sondage_survey_homepage:
    pattern:  /
    defaults: { _controller: SondageSurveyBundle:Page:index }

sondage_survey_display:
    pattern: survey/{id}
    defaults: { _controller: SondageSurveyBundle:Survey:display , id: 0 }
    requirements:
      _method:  GET
      id: \d+
sondage_survey_list:
    pattern: survey/list
    defaults: { _controller: SondageSurveyBundle:Survey:list }
sondage_survey_edit:
    pattern: survey/edit/{id}
    defaults: { _controller: SondageSurveyBundle:Survey:edit , id: 0 }
    requirements:
      _method:  GET|POST
      id: \d+
sondage_survey_add:
    pattern:  survey/add
    defaults: { _controller: SondageSurveyBundle:Survey:edit }
sondage_configuration:
    pattern: survey/configure
    defaults: { _controller: SondageSurveyBundle:Survey:configure }