sondage_survey_homepage:
    pattern:  /
    defaults: { _controller: SondageSurveyBundle:Page:index }

sondage_survey_display:
    pattern: survey/{id}
    defaults: { _controller: SondageSurveyBundle:Survey:display , id: 0 }
    requirements:
      _method:  GET
      id: \d+
sondage_survey_list:
    pattern: survey/list
    defaults: { _controller: SondageSurveyBundle:Survey:list }