sondage_authenticated_user:
    resource: "@SondageAuthenticatedUserBundle/Resources/config/routing.yml"
    prefix:   /

sondage_survey:
    resource: "@SondageSurveyBundle/Resources/config/routing.yml"
    prefix:   /